before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 7
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      -  itzg/mc-monitor:latest-amd64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      -  itzg/mc-monitor:latest-arm64
    dockerfile: Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
  - image_templates:
      -  itzg/mc-monitor:latest-arm-v7
    dockerfile: Dockerfile.release
    goarch: arm
    goarm: "7"
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
docker_manifests:
  - name_template:  itzg/mc-monitor:{{ .Tag }}
    image_templates:
      -  itzg/mc-monitor:latest-amd64
      -  itzg/mc-monitor:latest-arm64
      -  itzg/mc-monitor:latest-arm-v7
  - name_template:  itzg/mc-monitor:latest
    image_templates:
      -  itzg/mc-monitor:latest-amd64
      -  itzg/mc-monitor:latest-arm64
      -  itzg/mc-monitor:latest-arm-v7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^misc:'
