name: Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...
